swagger: "2.0"

info:
  title: "{{title}}"
  version: "1.0.0"

basePath: /v1

paths:
  /models/new:
    post:
      summary: Upload new model
      operationId: models.new
      consumes:
        - application/ubjson
      produces:
        - application/json
      parameters:
        - in: body
          name: model
          description: Model data and description
          schema:
            type: object
      responses:
        201:
          description: Created model's ID
          schema:
            type: object
            properties:
              model:
                type: string
        400:
          description: Error parsing request body
          schema:
            $ref: '#/definitions/ErrorResponse'

  /models/{modelID}:
    put:
      summary: Update model
      operationId: models.update
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: modelID
          in: path
          description: ID of the model to update
          required: true
          type: string
        - name: body
          in: body
          description: Model update description
          required: true
          schema:
            $ref: '#/definitions/ModelUpdate'
      responses:
        204:
          description: Model updated
        404:
          description: Model not found
          schema:
            $ref: '#/definitions/ErrorResponse'
    get:
      summary: Update model
      operationId: models.get
      produces:
        - application/json
      parameters:
        - name: modelID
          in: path
          description: ID of the model
          required: true
          type: string
      responses:
        200:
          description: Model status
          schema:
            $ref: '#/definitions/ModelStatus'
        404:
          description: Model not found
          schema:
            $ref: '#/definitions/ErrorResponse'

    delete:
      summary: Delete model
      operationId: models.delete
      parameters:
        - name: modelID
          in: path
          description: ID of the model to delete
          required: true
          type: string
      responses:
        204:
          description: Model deleted
        404:
          description: Model not found
          schema:
            $ref: '#/definitions/ErrorResponse'

definitions:
  ModelUpdate:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
      defaultPosition:
        $ref: '#/definitions/Position'
  ModelStatus:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
      importStatus:
        type: string
        enum: [processing, done, failed]
      defaultPosition:
        $ref: '#/definitions/Position'
  Position:
    type: object
    properties:
      sweref99:
        type: object
        properties:
          projection:
            type: string
            enum:
            - TM
            - 12_00
            - 13_30
            - 15_00
            - 16_30
            - 18_00
            - 14_15
            - 15_45
            - 17_15
            - 18_45
            - 20_15
            - 21_45
            - 23_15
          x:
            type: number
          y:
            type: number
          z:
            type: number
          roll:
            type: number
          pitch:
            type: number
          yaw:
            type: number
  ErrorResponse:
    type: object
    properties:
      message:
        type: string
