swagger: "2.0"

info:
  title: "{{title}}"
  version: "1.0.0"

basePath: /v1

paths:
  /models/new:
    post:
      summary: Upload new model
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "model"
        in: "formData"
        description: "Model description and optional position"
        type: string
      - name: "modelFile"
        in: "formData"
        description: "The model's binary geometry"
        required: true
        type: "file"
      responses:
        201:
          description: Created model's ID
          schema:
            type: object
            properties:
              model:
                type: string
                format: binary
        400:
          description: Error parsing request body
          schema:
            $ref: '#/definitions/ErrorResponse'
  /models/{modelId}:
    put:
      summary: Update model
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: modelId
          in: path
          description: ID of the model to update
          required: true
          type: string
        - name: modelUpdate
          in: body
          description: Model update description
          required: true
          schema:
            $ref: '#/definitions/ModelUpdate'
      responses:
        204:
          description: Model updated
        404:
          description: Model not found
          schema:
            $ref: '#/definitions/ErrorResponse'
    get:
      summary: Update model
      produces:
        - application/json
      parameters:
        - name: modelId
          in: path
          description: ID of the model
          required: true
          type: string
      responses:
        200:
          description: Model status
          schema:
            $ref: '#/definitions/ModelStatus'
        404:
          description: Model not found
          schema:
            $ref: '#/definitions/ErrorResponse'
    delete:
      summary: Delete model
      parameters:
        - name: modelId
          in: path
          description: ID of the model to delete
          required: true
          type: string
      responses:
        204:
          description: Model deleted
        404:
          description: Model not found
          schema:
            $ref: '#/definitions/ErrorResponse'
  /device/{deviceSerialNo}/models:
    post:
      summary: Set active model instances on the device
      consumes:
        - application/json
      parameters:
        - name: deviceSerialNo
          in: path
          description: ID of the model to update
          required: true
          type: string
        - in: body
          name: modelInstances
          description: TBD
          required: true
          schema:
            $ref: '#/definitions/ModelInstances'
      responses:
        204:
          description: Model instances successfully created
    get:
      summary: Get active model instances on the device
      produces:
        - application/json
      parameters:
        - name: deviceSerialNo
          in: path
          description: ID of the model to update
          required: true
          type: string
      responses:
        200:
          description: Current model instances on the device
          schema:
            $ref: '#/definitions/ModelInstances'
        404:
          description: Device or Model not found
          schema:
            $ref: '#/definitions/ErrorResponse'

definitions:
  ModelInstances:
    type: object
    properties:
      modelInstances:
        type: array
        items:
          $ref: '#/definitions/ModelInstance'
  ModelInstance:
    type: object
    properties:
      model:
        type: string
      name:
        type: string
      description:
        type: string
      hidden:
        type: boolean
      position:
        $ref: '#/definitions/Position'
    required: [model]
  ModelUpdate:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
      defaultPosition:
        $ref: '#/definitions/Position'
  ModelStatus:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
      importStatus:
        type: string
        enum: [processing, done, failed]
      defaultPosition:
        $ref: '#/definitions/Position'
  Position:
    type: object
    properties:
      sweref99:
        type: object
        properties:
          projection:
            type: string
            enum:
            - TM
            - 12 00
            - 13 30
            - 15 00
            - 16 30
            - 18 00
            - 14 15
            - 15 45
            - 17 15
            - 18 45
            - 20 15
            - 21 45
            - 23 15
          x:
            type: number
          y:
            type: number
          z:
            type: number
          roll:
            type: number
          pitch:
            type: number
          yaw:
            type: number
  ErrorResponse:
    type: object
    properties:
      message:
        type: string
