#!/bin/sh

#
# run tests using the python's unittest module
#
# this is a convinience wrapper around 'python -m unittest' command
#
tests="$@"
if test "$#" -ne 1; then
    # no tests specified, run all tests
    # that we can discover
    tests=discover
fi
python -m unittest $tests